name: Test Build Deploy GitHub Pages

on: [pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: yarn && yarn build:docs && cp CNAME website/dist/